import { PATH } from 'src/routes/path';

export const menus = [
  {
    key: 'SOURCE',
    name: '数据分配',
    hasChild: true,
    path: PATH.SOURCE_LIST,
    breadcrumbName: '数据分配',
    hidden: false,
    children: [
      {
        key: PATH.SOURCE_LIST,
        name: '来源管理',
        hasChild: false,
        icon: 'icon-data',
        path: PATH.SOURCE_LIST,
        breadcrumbName: '来源管理',
        hidden: false,
      },
      {
        key: 'SOURCE_VCG_IMAGE',
        name: '图片数据分配',
        hasChild: true,
        icon: 'icon-ic_image',
        breadcrumbName: '图片数据分配',
        hidden: false,
        children: [
          {
            key: PATH.SOURCE_VCG_IMAGE_TEXT,
            name: '创意类质量审核',
            hasChild: true,
            path: PATH.SOURCE_VCG_IMAGE_TEXT,
            breadcrumbName: '创意类质量审核',
            hidden: false,
          },
          {
            key: PATH.SOURCE_VCG_IMAGE_KEYWORD,
            name: '创意类关键词审核',
            hasChild: true,
            path: PATH.SOURCE_VCG_IMAGE_KEYWORD,
            breadcrumbName: '创意类关键词审核',
            hidden: false,
          },
          {
            key: PATH.SOURCE_VCG_IMAGE_SENSITIVE,
            name: '创意类安全审核',
            hasChild: true,
            path: PATH.SOURCE_VCG_IMAGE_SENSITIVE,
            breadcrumbName: '创意类安全审核',
            hidden: false,
          },
          {
            key: PATH.SOURCE_CFP_IMAGE_LIST,
            name: '编辑类审核',
            hasChild: true,
            path: PATH.SOURCE_CFP_IMAGE_LIST,
            breadcrumbName: '编辑类审核',
            hidden: false,
          },
        ],
      },
    ],
  },
  {
    key: 'SYSTEM_REVIEW',
    name: '全部资源',
    hasChild: true,
    path: PATH.SYSTEM_REVIEW_VCG_IMAGE_TEXT,
    breadcrumbName: '全部资源',
    hidden: false,
    children: [
      {
        key: 'SYSTEM_REVIEW_IMAGE',
        name: '图片审核',
        hasChild: true,
        icon: 'icon-ic_image',
        breadcrumbName: '图片审核',
        hidden: false,
        children: [
          {
            key: PATH.SYSTEM_REVIEW_VCG_IMAGE_TEXT,
            name: '创意类质量审核',
            hasChild: false,
            path: PATH.SYSTEM_REVIEW_VCG_IMAGE_TEXT,
            breadcrumbName: '创意类质量审核',
            hidden: false,
          },
          {
            key: PATH.SYSTEM_REVIEW_VCG_IMAGE_KEYWORD,
            name: '创意类关键词审核',
            hasChild: false,
            path: PATH.SYSTEM_REVIEW_VCG_IMAGE_KEYWORD,
            breadcrumbName: '创意类关键词审核',
            hidden: false,
          },
          {
            key: PATH.SYSTEM_REVIEW_VCG_IMAGE_SENSITIVE,
            name: '创意类安全审核',
            hasChild: false,
            path: PATH.SYSTEM_REVIEW_VCG_IMAGE_SENSITIVE,
            breadcrumbName: '创意类安全审核',
            hidden: false,
          },
          {
            key: PATH.SYSTEM_REVIEW_CFP_IMAGE_LIST,
            name: '编辑类审核',
            hasChild: false,
            path: PATH.SYSTEM_REVIEW_CFP_IMAGE_LIST,
            breadcrumbName: '编辑类审核',
            hidden: false,
          },
        ],
      },
    ],
  },
  {
    key: 'USER_REVIEW',
    name: '我的审核',
    hasChild: true,
    path: PATH.USER_REVIEW_VCG_IMAGE_TEXT,
    breadcrumbName: '我的审核',
    hidden: false,
    children: [
      {
        key: 'USER_REVIEW_IMAGE',
        name: '图片审核',
        hasChild: true,
        icon: 'icon-ic_image',
        breadcrumbName: '图片审核',
        hidden: false,
        children: [
          {
            key: PATH.USER_REVIEW_VCG_IMAGE_TEXT,
            name: '创意类质量审核',
            hasChild: false,
            path: PATH.USER_REVIEW_VCG_IMAGE_TEXT,
            breadcrumbName: '创意类质量审核',
            hidden: false,
          },
          {
            key: PATH.USER_REVIEW_VCG_IMAGE_KEYWORD,
            name: '创意类关键词审核',
            hasChild: false,
            path: PATH.USER_REVIEW_VCG_IMAGE_KEYWORD,
            breadcrumbName: '创意类关键词审核',
            hidden: false,
          },
          {
            key: PATH.USER_REVIEW_VCG_IMAGE_SENSITIVE,
            name: '创意类安全审核',
            hasChild: false,
            path: PATH.USER_REVIEW_VCG_IMAGE_SENSITIVE,
            breadcrumbName: '创意类安全审核',
            hidden: false,
          },
          {
            key: PATH.USER_REVIEW_CFP_IMAGE_LIST,
            name: '编辑类审核',
            hasChild: false,
            path: PATH.USER_REVIEW_CFP_IMAGE_LIST,
            breadcrumbName: '编辑类审核',
            hidden: false,
          },
        ],
      },
    ],
  },
];
